version: '3.9'

services:
## Instalación y actualización de dependencias
  init-client:
    working_dir: "/app"
    image: "node:16.16.0-alpine3.16"
    profiles: 
      - "init"
      - "init-client"
    volumes:
      - "./frontend:/app"
    command: npm install --legacy-peer-deps
  init-server:
    working_dir: "/app"
    image: "php-gedure:1.0.1"
    profiles: 
      - "init"
      - "init-server"
    volumes:
      - "./backend:/app"
    depends_on:
      - mysql
    command:
      - /bin/sh
      - -c
      - |
        composer install
        php artisan key:generate
        php artisan migrate --seed
        php artisan passport:install
        php artisan storage:link
  update-server:
    working_dir: "/app"
    image: "php-gedure:1.0.1"
    profiles: 
      - "update"
      - "update-server"
    volumes:
      - "./backend:/app"
    command: composer update

## Servidor de testing
  test-server:
    working_dir: "/app"
    image: "php-gedure:1.0.1"
    profiles: 
      - "test"
    volumes:
      - "./backend:/app"
    command: php artisan test --filter=${FILTER_TEST}


## Servidor de DB
  mysql:
    image: "mysql:5.7.38-oracle"
    profiles:
      - "server"
      - "init-server"
      - "init"
      - "mysql"
    environment:
      - MYSQL_DATABASE=gedure
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ~/.docker/mysql-gedure:/var/lib/mysql
  phpmyadmin:
    image: "phpmyadmin:5.2.0-apache"
    profiles:
      - "phpmyadmin"
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql

## Servidores de desarollo
  client:
    working_dir: "/app"
    image: "node:16.16.0-alpine3.16"
    profiles:
      - "client"
    volumes:
      - "./frontend:/app"
    ports:
      - "3000:3000"
    command: npm start
  server:
    working_dir: "/app"
    image: "php-gedure:1.0.1"
    profiles: 
      - "server"
    volumes:
      - "./backend:/app"
    ports:
      - "80:8000"
    depends_on:
      - mysql
    command: php artisan serve --host=0.0.0.0
  websockets:
    working_dir: "/app"
    image: "php-gedure:1.0.1"
    profiles: 
      - "server"
    volumes:
      - "./backend:/app"
    ports:
      - "6001:6001"
    depends_on:
      - mysql
    command: php artisan websockets:serve
  schedule:
    working_dir: "/app"
    image: "php-gedure:1.0.1"
    profiles: 
      - "server"
    volumes:
      - "./backend:/app"
    depends_on:
      - server
    command: 
      - /bin/sh
      - -c
      - |
        php artisan cache:clear
        php artisan schedule:work