version: '3.9'

services:
## Servidor de DB
  mysql:
    image: "mysql:5.7.38-oracle"
    profiles:
      - "server"
      - "phpmyadmin"
    environment:
      - MYSQL_DATABASE=gedure
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ~/.docker/mysql-gedure:/var/lib/mysql
  phpmyadmin:
    image: "phpmyadmin:5.2.0-apache"
    profiles:
      - "phpmyadmin"
    ports:
      - "8080:80"
    depends_on:
      - "mysql"
    environment:
      - PMA_HOST=mysql

## Contenedor de testing
  tests:
    working_dir: "/app"
    image: "php-gedure:2.0.0"
    profiles: 
      - "test"
    volumes:
      - "./backend:/app"
    command: php artisan test --filter=${FILTER_TEST}

## Contenedores de desarrollo
  php-fpm:
    image: "php-gedure:2.0.0"
    profiles:
      - "server"
    volumes:
      - ./backend:/app
      - ./docker/php/upload.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - "mysql"
  nginx:
    image: "nginx:1.23.3"
    profiles: 
      - "server"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/server.conf
      - ./docker/nginx/cert:/etc/ssl
      - ./backend:/app
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "php-fpm"
      - "websockets"
  websockets:
    working_dir: "/app"
    image: "php-gedure:2.0.0"
    profiles: 
      - "server"
    volumes:
      - "./backend:/app"
      - ./docker/php/upload.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - "php-fpm"
    command: php artisan websockets:serve
  schedule:
    working_dir: "/app"
    image: "php-gedure:2.0.0"
    profiles: 
      - "server"
    volumes:
      - "./backend:/app"
      - ./docker/php/upload.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - "nginx"
    command: 
      - /bin/sh
      - -c
      - |
        php artisan cache:clear
        php artisan schedule:work