<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class NewsTable extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$news = array(
			array('id' => '1','title' => 'ORIENTACIONES','content' => 'Buenas tardes estimados estudiantes y representantes, espero se encuentren en familia siguiendo con todas las medidas preventivas en relación a esta Pandemia mundial a la que nos sumamos actualmente. El llamado es a mantener  la calma y a Orar por el mundo todos juntos. ','img' => '["assets\\/src\\/noticias\\/img\\/1.jpg"]','fecha' => '2020-03-17 16:45:22','owner' => 'A-rhadys'),
			array('id' => '2','title' => 'INFORMACIÓN IMPORTANTE','content' => 'La UEPAPEP "LA CANDELARIA" bajo la Dirección del Profesor Roberto Puerta   Conjuntamente con su equipo de trabajo, Siguiendo Orientaciones de  Zona Educativa y Jefe Circuital exhorta a todos los padres, madres, representantes a mantener la calma en relación a la culminación del II Momento e inicio del III Momento. En la institución el II Momento estaba previsto Culminar el 20/03/2020 por lo que esta era la ultima semana. El llamado es a lo siguiente: 1) Cualquier evaluación asignada por los diferentes docentes  deben realizarlas como estaba previsto. 2) Las actividades serán recibidas al momento de incorporarnos nuevamente a las aulas de clase. 3) Todos los estudiantes deben realizar el Portafolio con las asignaciones orientadas en el programa" UNA FAMILIA UNA ESCUELA"  que se transmite de lunes a viernes por Venezolana de Televisión a las 10:00 am donde deben estar pendiente de su nivel, en este caso Media General y Técnica,  y en el canal TV FANB a las 3:00 pm. 4) Los estudiantes que tienen evaluaciones pendientes por reposos médicos y su docente no le asignó la estrategia deben de igual forma realizar el portafolio y será tomado como evaluación. ','img' => '["assets\\/src\\/noticias\\/img\\/2.jpg"]','fecha' => '2020-03-17 17:13:26','owner' => 'A-rhadys'),
			array('id' => '3','title' => 'INFORMACIÓN IMPORTANTE','content' => 'La UEPAPEP "LA CANDELARIA" bajo la Dirección del Profesor Roberto Puerta   Conjuntamente con su equipo de trabajo, Siguiendo Orientaciones de  Zona Educativa y Jefe Circuital exhorta a todos los padres, madres, representantes a mantener la calma en relación a la culminación del II Momento e inicio del III Momento. En la institución el II Momento estaba previsto Culminar el 20/03/2020 por lo que esta era la ultima semana. El llamado es a lo siguiente: 1) Cualquier evaluación asignada por los diferentes docentes  deben realizarlas como estaba previsto. 2) Las actividades serán recibidas al momento de incorporarnos nuevamente a las aulas de clase. 3) Todos los estudiantes deben realizar el Portafolio con las asignaciones orientadas en el programa" UNA FAMILIA UNA ESCUELA"  que se transmite de lunes a viernes por Venezolana de Televisión a las 10:00 am donde deben estar pendiente de su nivel, en este caso Media General y Técnica,  y en el canal TV FANB a las 3:00 pm. 4) Los estudiantes que tienen evaluaciones pendientes por reposos médicos y su docente no le asignó la estrategia deben de igual forma realizar el portafolio y será tomado como evaluación. ','img' => '["assets\\/src\\/noticias\\/img\\/3.jpg"]','fecha' => '2020-03-17 17:22:39','owner' => 'A-rhadys'),
			array('id' => '5','title' => 'INFORMACIÓN IMPORTANTE','content' => ' PRIMARIA:</br>','img' => '["assets\\/src\\/noticias\\/img\\/5.jpg","assets\\/src\\/noticias\\/img\\/6.jpg","assets\\/src\\/noticias\\/img\\/7.jpg","assets\\/src\\/noticias\\/img\\/8.jpg","assets\\/src\\/noticias\\/img\\/9.jpg"]','fecha' => '2020-03-17 17:54:00','owner' => 'A-rhadys'),
			array('id' => '7','title' => 'ASIGNACIÓN PARA EL PORTAFOLIO','content' => 'AMOR A LA PATRIA:</br>Área de Formación: GHC</br>TEMA: Preservación de la Vida en el Planeta. Vida y Salud</br>Actividad: Junto a la familia elaborar una lista de Medidas Preventivas sobre el cov.19. Producción escrita sobre los países por donde se inicio la enfermedad, causa, consecuencia. Cantidad de casos anunciados por país.</br>NO OLVIDES COLOCAR LA FECHA A CADA ACTIVIDAD.</br>A DIARIO VER EL PROGRAMA. PADRES Y REPRESENTANTES APOYAR A SUS HIJOS.','img' => '["assets\\/src\\/noticias\\/img\\/11.jpg"]','fecha' => '2020-03-17 18:21:19','owner' => 'A-rhadys'),
			array('id' => '9','title' => 'ORIENTACIONES ','content' => 'AREA DE FORMACIÓN: MATEMÁTICA</br>TEMA: OPERACIONES CON NÚMEROS RACIONALES</br>INVESTIGAR EL TEMA </br>EJERCICIOS. </br>RESOLVER:</br>1)    4/3  +   7/3=</br></br>2)     8/9   +   3/9  =</br></br></br>3)     5/4    +    7/5=</br></br></br>4)       3/8  +     6/7 =</br>','img' => '["assets\\/src\\/noticias\\/img\\/12.jpg"]','fecha' => '2020-03-18 15:22:54','owner' => 'A-rhadys'),
			array('id' => '11','title' => 'ACTIVIDAD','content' => 'TEMA: PROCESO REPRODUCTIVO DE LA GALLINA</br>ACTIVIDAD:</br>1. Realiza el esquema del aparato reproductor de la gallina. </br>2. Puedes ampliar con lecturas acerca de la higiene y mantenimiento de la gallina.  Recuerda escribir la fecha de las actividades realizadas. </br>3. Guarda en tu portafolio esta actividad. </br>Nota: ESTAS TAREAS VAN DIRIGIDAS A TODOS LOS ESTUDIANTES DE 1er año  a  5 to año. </br>Los Estudiantes de 6to año están atendidos por la Prof. Erika Arguinzones con otras actividades. </br>','img' => '["assets\\/src\\/noticias\\/img\\/13.55"]','fecha' => '2020-03-19 13:21:38','owner' => 'A-rhadys'),
			array('id' => '12','title' => 'ÁREA: CASTELLANO','content' => 'TEMA: USO INADECUADO Y ADECUADO DEL INTERNET Y DE LAS REDES SOCIALES. </br>USO DE LA TECNOLOGÍA DE MANERA POSITIVA Y NEGATIVA.</br>ACTIVIDAD: Investiga cómo se realiza un artículo de prensa. </br>1er Año: Redacta un artículo de prensa donde se refleje el año de aparición del Covid -19, causas y Consecuencias.</br></br>2do Año: Redacta un artículo de prensa donde se refleje el año de aparición del Covid -19, causas y Consecuencias y síntomas.</br></br>3er Año: Redacta un artículo de prensa donde se refleje el año de aparición del Covid -19, causas,  Consecuencias , síntomas y lugares afectados en el mundo con el covid-19.</br></br>4to Año: Redacta un artículo de prensa donde se refleje el año de aparición del Covid -19, causas,  Consecuencias , síntomas , lugares afectados en el mundo y Prevención. </br></br>5to Año: Redacta un artículo de prensa donde se refleje el año de aparición del Covid -19, causas,  Consecuencias , síntomas , lugares afectados en el mundo  y Prevención. Elabora 5 HASHTAG  relacionados con el tema Covid-19. Antes investiga que es un Hashtag. </br></br>Recuerda escribir la fecha de todas las actividades y guardar en tu portafolio.</br></br>','img' => '["assets\\/src\\/noticias\\/img\\/14.jpg"]','fecha' => '2020-03-20 16:54:26','owner' => 'A-rhadys'),
			array('id' => '13','title' => 'III MOMENTO ','content' => 'ORIENTACIONES PARA TODOS LOS ESTUDIANTES DE 1er año a 5to año de  las áreas en común. </br>Siguiendo las orientaciones el día lunes 23 de marzo inicia el III momento para darle continuidad a las actividades académicas, según este cronograma:</br></br>CANAL DE TRANSMISIÓN : VENEZOLANA DE TELEVISIÓN A LAS 10:00am</br></br>Día lunes: Identidad y Soberanía, Orientación y Convivencia, Geografía e Historia y Ciudadanía. Arte y Patrimonio. Seguridad para la Soberanía Nacional.</br></br>Día martes: Ciencia y Salud, Ciencias Naturales, Biología,Química, Física y Ciencias de la Tierra.</br></br>Día miércoles: Matemática para la vida.</br>Día jueves:Proyecto, realizar una estrategia didáctica para el cuido del ambiente en tu municipio.</br></br>Día viernes: Cultura, educación física y recreación. </br>Recuerda identificar las áreas de conocimiento y colocar la fecha de cada actividad.</br></br>EFEMÉRIDES: EL 23 de marzo nace Vicente Salias (1776) , periodista, médico y escritor Venezolano. Autor de la Letra GLORIA AL BRAVO PUEBLO Himno de la República Bolivariana de Venezuela. </br>25 de marzo: Primera aparición de la Virgen de Betania (1976)</br></br>','img' => '["assets\\/src\\/noticias\\/img\\/15.jpg"]','fecha' => '2020-03-21 17:44:24','owner' => 'A-rhadys'),
			array('id' => '14','title' => 'ÁREA GEOGRAFÍA HISTORIA Y CIUDADANÍA. FO','content' => 'LA VIDA EN LA FRONTERA  Y SITUACIÓN LIMÍTROFE</br>TEMAS: Diferencia entre frontera y límite.</br>Previa investigación con la ayuda de tus padres, representantes o responsables y las orientaciones en el programa Cada Familia una Escuela realiza lo siguiente:</br></br>MEDIA GENERAL: 1ERO A 3ER AÑO</br>Actividad:</br>1.- Elabora un Mapa  de Venezuela señalando los Puntos Cardinales y Límites de Venezuela. </br>2.- Escriba 3 medidas de prevención en la frontera para evitar el Covid-19</br></br>MEDIA TÉCNICA 4to y 5to año </br>Actividad:</br>1.- Elabora un mapa de Venezuela señalando los Puntos Cardinales, Límites de Venezuela y Extensión territorial. </br>2.- Menciona 3 problemas Fronterizos. </br>3.- Escribe 3 medidas de prevención en la frontera para el Covid-19</br>RECUERDA ESTA ACTIVIDAD CORRESPONDE AL III MOMENTO.</br>No olvides colocar la fecha de cada actividad y guardar en tu portafolio.</br>','img' => '["assets\\/src\\/noticias\\/img\\/16.jpg"]','fecha' => '2020-03-23 17:44:20','owner' => 'A-rhadys'),
			array('id' => '15','title' => 'ÁREA CIENCIAS NATURALES','content' => 'TEMA: PRESERVACIÓN DE LA VIDA EN EL PLANETA TIERRA.</br>AMBIENTE BIODIVERSIDAD Y SOBERANÍA ALIMENTARIA.</br></br>ACTIVIDAD 1ER AÑO Y 2DO AÑO</br>Con la ayuda de padre,madre,representante o responsable investiga lo siguiente: </br>A) Soberanía alimentaria  b) Hábitat  c) Ecosistema  d)Especies  f)Biodiversidad</br>2.- Elabora un cuadro con 6 alimentos que poseas en tu casa, señalando lo siguiente:</br>a) Nombre Científico b) Nombre común c) Estados donde se producen</br></br>ACTIVIDAD 3ER AÑO ÁREA FÍSICA</br>TEMA: SONIDO Y BIODIVERSIDAD</br>3ER AÑO "A" : 1.- Elabore un mapa conceptual de la clasificación de las ondas sonoras en el ambiente. </br>3ER AÑO "B" : 1.- Elabore un mapa mental de la propagación del sonido en la naturaleza.</br>3ER AÑO "C": 1.- Elabore un cuadro sobre los elementos y propiedades de las ondas sonoras en el planeta.</br>PARA 3ER AÑO "A", "B" "C"</br>2.-Dibuje el aparato receptor de sonido, el oído y sus partes. Nombrar normas de cuidado del oído. </br>3.- Diseñe una tabla de calorías de los alimentos: proteínas, carbohidratos y grasas.','img' => '["assets\\/src\\/noticias\\/img\\/17.jpg"]','fecha' => '2020-03-24 15:30:30','owner' => 'A-rhadys'),
			array('id' => '17','title' => 'MATEMÁTICA','content' => 'Tema: Números Racionales</br>Socializa con tu hijo: ¿Qué consumes del Trompo Alimenticio en casa?</br>Actividad para  1er año, 2do y 3er año</br>RESUELVE LAS SIGUIENTES MULTIPLICACIONES</br>a)  4/8  .  7/6  =             b)    9/7. 6/2 =</br>RESUELVE LAS SIGUIENTES DIVISIONES</br>a) 8/3  :  4/7 =               b) 9/8   :   8/3    = </br></br>Los estudiantes de 4to y 5to año el prof. Yonny esta preparando una </br>guía de matemática. De igual forma los Profesores Norelys Vegas</br>Rafael Ortiz, Eidea Moreno, Oswaldo Contreras.</br></br>Fundamentos de Contabilidad: </br>ESTUDIANTES DE 2do AÑO.</br>Elabore un glosario con material reciclado con los siguientes términos:</br>Contabilidad, activo, pasivo, capital, asiento, cargo, abono, crédito</br>débito, saldo, obligaciones, nomina, transacciones, ventas, joya, utilidad,</br>factura, deuda, bienes, derecho, haber, debe, moneda, deudor,pérdida</br>servicio,rif, egreso, ingreso, gasto, inventario, banco, ganancia, </br>impuestos, cheque, acreedor</br></br>','img' => '["assets\\/src\\/noticias\\/img\\/18.jpg"]','fecha' => '2020-03-25 13:35:34','owner' => 'A-rhadys'),
			array('id' => '19','title' => 'CONVOCATORIA','content' => 'DIRIGIDA A LOS PADRES, MADRES, REPRESENTANTES O RESPONSABLES.</br>1ER AÑO A 5TO AÑO.</br>SE INFORMA QUE EL DÍA MIÉRCOLES  01/04/2020  DESDE LAS 7:30AM A 10:00AM</br>EN LA UEP APEP LA CANDELARIA SE ESTARÁN RECIBIENDO LAS ACTIVIDADES QUE ESTÁN PENDIENTE DEL II MOMENTO. QUE DEBÍAN SER ENTREGADAS A LOS DOCENTES Y FUERON ASIGNADAS.  DEBEN ASISTIR LOS REPRESENTANTES A LA ENTREGA. IDENTIFICAR LOS TRABAJOS CON NOMBRE APELLIDO Y SECCIÓN.  </br>ASISTIR CON LAS MEDIDAS DE SEGURIDAD SOCIAL: TAPA BOCA Y DE SER POSIBLE GUANTES. </br></br>NO ES REUNIÓN DE REPRESENTANTE .  ES ENTREGA DE TRABAJOS.</br></br></br>','img' => '["assets\\/src\\/noticias\\/img\\/19.jpg"]','fecha' => '2020-03-26 18:43:10','owner' => 'A-rhadys'),
			array('id' => '20','title' => 'CASTELLANO','content' => 'Prof. lisbelia Corrales. 4TO  A,B,C.</br>Para los estudiantes que no realizaron la Obra de Teatro. </br>SE CAMBIA LA ESTRATEGIA  POR UN ANÁLISIS REFLEXIVO DE LA PELÍCULA " MILAGROS DEL CIELO" BAJARLA POR YOUTUBE. DOS CUARTILLAS O PAGINAS DONDE EXPLIQUE EL SIGNIFICADO DE LA VIDA Y MUERTE, EL AMOR Y LA UNIÓN FAMILIAR, EL ABORTO Y LA FE EN DIOS.</br>Estudiantes que faltaron:</br>4 A: SILVA, BERROTERAN, ANGULO, BESTARD, CACERES, RUBIANES,MILLA,</br>MACHADO,BACALAU,IBARRA,SEIJAS,MENDOZA, PEREZ,MAGALLANES,TOCUYO,</br>GASCON, OJEDA, CASTRO, GANZÁLEZ.</br>4B: TREJO,GUTIERREZ, RANGEL,APONTE,SANZ,LINARES, ANGEL,MATOS,</br>AGUERO,BAPTISTA,BRICEÑO, CASTILLO LAUCHO LATAN.</br>4C: ALARCÓN.</br> </br>EVIARLO VÍA CORREO: cascocentralturmero@gmail.com a mas tardar el martes 31/03/2020. ','img' => '["assets\\/src\\/noticias\\/img\\/20.jpg"]','fecha' => '2020-03-26 19:45:46','owner' => 'A-rhadys'),
			array('id' => '21','title' => 'CASTELLANO','content' => 'Prof. Zuleyma Benavidez:</br>ACTIVIDAD III MOMENTO 1er año A,B,C</br>TEMA: La Comunicación.</br>1.- Definición, importancia, elementos de la comunicación.</br>Comunicación Verbal y no Verbal.</br>2.-Realizar un Esquema con el contenido investigado</br>3.- Elaborar un cuento lustrado relacionado con el Covid-19.  Debe llevar los siguientes elementos: Inicio, desarrollo y cierre.</br>2do A, B, C</br>ACTIVIDAD:</br>1.- Realizar un Trabajo Escrito. (Portada, Índice, Introducción, Desarrollo, Conclusión y Bibliografía. </br>Tema: El LIBRO</br>Evolución, partes del libro, enciclopedia, atlas, diccionario. </br>2.- Elaborar el una hoja 1 poesía  sobre el Covid-19. </br></br>3er año A,B,C.</br>ACTIVIDAD:</br></br>1.- Realizar un cuadro sinóptico de cualquiera de los siguientes temas:</br>a) La Narrativa Literaria</br>b) Los Géneros Literarios</br>c) Elementos del texto narrativo literario</br>2.- Elaborar una Fábula con el tema Coronavirus, destacas una Moraleja al final del trabajo.</br>ARCHIVAR EN TU PORTAFOLIO.</br>','img' => '["assets\\/src\\/noticias\\/img\\/21.jpg"]','fecha' => '2020-03-28 15:43:13','owner' => 'A-rhadys'),
			array('id' => '22','title' => 'REPROGRAMACIÓN','content' => 'SE INFORMA QUE  A PARTIR DEL MIÉRCOLES SE ESTARÁ ENTREGANDO ALMUERZO A TODOS NUESTROS ESTUDIANTES. POR LO QUE DEBEN LLEVAR EL ENVASE PARA SERVIRLO. ES IMPORTANTE RECIBIR EL BENEFICIO PARA GARANTIZAR EL DESPACHO A NUESTRA INSTITUCIÓN. </br></br>POR TAL MOTIVO LA ATENCIÓN SERA DE 10:30 am a 12:00 m </br></br>RECEPCIÓN DE TRABAJOS Y ENTREGA DE ALMUERZO. </br></br>ASISTE CON LAS MEDIDAS DE PREVENCIÓN SOCIAL.</br></br>','img' => '["assets\\/src\\/noticias\\/img\\/22.jpg"]','fecha' => '2020-03-30 10:40:54','owner' => 'A-rhadys'),
			array('id' => '23','title' => 'ÁREA G.H. Y C','content' => 'TEMA: La preservación de la vida en el planeta, la salud y vivir bien.</br>TEMA: PATRIMONIO CULTURAL Y NATURAL</br></br>ACTIVIDAD PARA MEDIA GENERAL 1ero a 3ero.</br>1.- Elabora un cuadro señalando   tres (3)  Patrimonios Culturales y  (3) Naturales en tu estado o en Venezuela, Señalando lo siguiente:</br>a)Nombre del Patrimonio cultural y Natural.</br>b) Ubicación</br>c) Breve descripción del Patrimonio.</br></br>ACTIVIDAD PARA MEDIA TÉCNICA  4to y 5to año</br></br>Elabore un ensayo de dos cuartillas o páginas donde se refleje la importancia del cuidado y preservación del patrimonio cultural y natural en Venezuela y el Mundo. </br></br>RECUERDA QUE ESTAS SON ACTIVIDADES DEL III MOMENTO IDENTIFICA CON TU NOMBRE Y ARCHIVA EN EL PORTAFOLIO. </br>','img' => '["assets\\/src\\/noticias\\/img\\/23.jpg"]','fecha' => '2020-03-30 13:23:38','owner' => 'A-rhadys'),
			array('id' => '25','title' => 'CIENCIAS NATURALES ','content' => '</br>TEMA: USO RACIONAL DEL AGUA, EL PETROLEO Y LA ENERGÍA.</br></br>ACTIVIDAD PARA MEDIA GENERAL 1er y 2do  AÑO SECCIÓN “A”,”B”,”C”</br></br>1.- Elabore un tríptico que señale el uso racional y responsable del agua.</br></br>ASIGNATURA FÍSICA</br>ACTIVIDAD PARA 3er AÑO Sección “A”,”B”,”C. </br></br>1.- Elaborar un Esquema de los procesos energéticos al generar electricidad a partir de combustibles fósiles.</br>','img' => '["assets\\/src\\/noticias\\/img\\/24.jpg"]','fecha' => '2020-03-31 14:46:20','owner' => 'A-rhadys'),
			array('id' => '26','title' => 'IMPORTANTE LEER','content' => 'Estimados representantes La UEP APEP LA CANDELARIA  agradece la receptividad en la entrega de trabajos el día de hoy, continuamos trabajando por nuestros niños, niñas y adolescentes.</br> </br>Se entrego almuerzo y mañana continuamos garantizando el almuerzo de 10:00 am a  11:00 am. </br></br>A pesar que se informó que el portafolio correspondía al III Momento se recibieron y los docentes revisaran las actividades. </br></br>Hasta el viernes 03/04/20 las evaluaciones del programa Cada Familia una Escuela serán consideradas evaluaciones para el III Momento.  </br></br>Los docentes de la institución enviaran por este medio, grupos de whatsapp, correo electrónico, entre otros las asignaciones adaptadas al grado y nivel de Educación  Técnica, de 1ero a 5to año. </br></br>Padre, madre, representantes o responsables, revisa el CELULAR Y REDES SOCIALES  de tu hijo. Estar atentos a lo que publican o conversan, sobre todo los más pequeños.</br></br>','img' => '["assets\\/src\\/noticias\\/img\\/25.jpg"]','fecha' => '2020-04-01 20:44:33','owner' => 'A-rhadys'),
			array('id' => '28','title' => 'VIERNES DE CONCILIO','content' => 'Este viernes 03 de abril la Iglesia Católica da inicio a la Semana Santa.</br></br>El Viernes de Dolores o Viernes de Pasión, también conocido anteriormente como el Viernes de Concilio, da inicio a la conmemoración de la muerte de Cristo en el Calvario. Recuerda el sufrimiento que acompañó a María durante la muerte de su hijo.</br></br>“Se le llama Viernes de Concilio porque ese día se reunió el poder supremo y decidió condenar a Jesús a muerte. También, es momento propicio para recordar el dolor de la Virgen María por la sentencia a su Hijo”.</br></br>LA UEP APEP. LA CANDELARIA  INVITA A TODAS LAS FAMILIAS A VIVIR EN CRISTO ESTA SEMANA SANTA </br>En este tiempo tan difícil renovemos la fe en Dios y vivamos cada momento en oración especialmente por que este virus Covid-19 sea superado en el mundo. ','img' => '["assets\\/src\\/noticias\\/img\\/26.jpg"]','fecha' => '2020-04-03 17:27:30','owner' => 'A-rhadys'),
			array('id' => '29','title' => 'DOMINGO DE RAMOS','content' => '</br>El Domingo de Ramos es el día en que los cristianos conmemoran la entrada de Jesús en Jerusalén y su aclamación como Hijo de Dios. </br>El Domingo de Ramos es el acontecimiento que marca el fin de la Cuaresma y el inicio de la Semana Santa, tiempo en que se celebra la pasión, crucifixión, muerte y resurrección de Cristo.</br></br></br>NOTA: Se les recuerda que contamos con el almuerzo en la institución lo cual puede retirar  el representante  de 11: am  a 12:00 m. </br></br>A partir de el lunes 06/04/20 se estarán publicando las actividades de los docentes especificando grado y sección según la asignatura.','img' => '["assets\\/src\\/noticias\\/img\\/27.jpg"]','fecha' => '2020-04-05 09:46:13','owner' => 'A-rhadys'),
			array('id' => '30','title' => 'LENGUAJE','content' => 'Docente: Lisbelia Corrales</br>Correo Gmail: Cascocentralturmero@gmail.com</br>Año: 5to Sección A-B-C</br>Tema: La Leyenda venezolana</br>Instrucciones: Preferible por correo #Quédate en casa</br>1-Las actividades son individuales </br>2-Se pueden entregar por correo o en físico</br>3-Cumplir con la hora y el día pautado a las 8:00am </br>4-No copiarse, realizar con sus propias palabras</br>5-Cada Sección tiene una leyenda diferente para el desarrollo todas de las actividades.</br>          5 año Sección  A    Florentino y el Diablo </br>          5 año Sección  B    El Silbón y Juan Hilario</br>          5 año Sección  C    El hachador Perdido </br> TEMA1: Leyendas, contrapunteo .Biografía de Alberto Arévalo Torrealba	</br>ACTIVIDAD: I Parte:  Elabore un mapa mental relacionado con todo lo que considere acerca del tema, concepto, características entre otros, y una biografía de Alberto Arévalo Torrealba.</br>II PARTE  responder estas preguntas relacionadas con la leyenda que le corresponda.</br>1-En qué estado se realiza </br>2-Señala las características del paisaje </br>3- Que aspecto religioso se presenta? </br>4-Describe a cada personaje </br>5-Explica el nivel del lenguaje </br>6-Que poder tiene la oración.</br>ESTRATEGIA DE 25% FECHA PARA ENVIAR ACTIVIDAD POR CORREO HASTA EL 22/04/20 ','img' => '["assets\\/src\\/noticias\\/img\\/28.jpg"]','fecha' => '2020-04-06 14:47:07','owner' => 'A-rhadys'),
			array('id' => '31','title' => 'LENGUAJE','content' => 'Docente: Lisbelia Corrales</br>Correo Gmail: Cascocentralturmero@gmail.com</br>Docente: Lisbelia Corrales </br>Correo Gmail: Cascocentralturmero@gmail.com</br>Año: 4to Sección A-B-C</br>Instrucciones: Preferible por correo # Quédate en casa</br>1-Realizar lecturas, investigaciones</br>2-El trabajo o la actividad son individual </br>3-Deber realizar, analizar, interpretaciones (no copiar de otros)</br>4-Puede ser entregado por correo o en físico</br>5-Cumplir con la fecha y hora establecidas 8:00am</br>6-Realizar la actividad en el tiempo establecido</br></br>TEMA 1: Periodos Históricos de los movimientos literarios:</br>ACTIVIDAD 1: Mapa conceptual, Señala 4 característica de cada movimiento Edad Media, Antigua, Moderna y contemporánea.</br>1- Renacimiento            4.- Romanticismo</br>2- Barroco                         5- Modernismo</br>3- Neoclasicismo            6- Costumbrismo </br>7- Vanguardismo </br>ESTRATEGIA 25% FECHA DE ENVÍO POR CORREO HASTA EL 24/04/20','img' => '["assets\\/src\\/noticias\\/img\\/29.jpg"]','fecha' => '2020-04-06 14:56:26','owner' => 'A-rhadys'),
			array('id' => '32','title' => 'PRÁCTICA DE OFICINA I','content' => 'Docente: Lisbelia Corrales</br>Correo Gmail: Cascocentralturmero@gmail.com</br>Año: 4to Sección  C</br>Instrucciones: Preferible por correo # Quédate en casa</br>TEXTO SUGERIDO PARA TODAS LAS ACTIVIDADES</br>Mujica, D. y Suarez M. Nociones básicas de oficina (2007) Corporación Marca</br>Tema: Cooperativismo </br>III Lapso</br>Instrucciones:</br>1-Cumplir con las fechas indicadas, así como la hora 8:00am en el liceo. Las fechas anteriores son para investigar.</br>2-El trabajo o actividad puede ser enviada por correo o en físico. Preferible por correo        # Quédate en casa</br>3-Es individual</br>4-Realizar tu creación, no copiar de otros </br>5-Realiza lecturas o investigar, Actividades Lunes y Viernes</br></br>TEMA: Relación entre la simbología, valores y principios del cooperativismo</br>ACTIVIDAD 1: Elabore un Mapa Mental con el tema investigado.</br></br>ESTRATEGIA 15% FECHA DE ENTREGA HASTA EL 23/04/20.</br>','img' => '["assets\\/src\\/noticias\\/img\\/30.jpg"]','fecha' => '2020-04-06 15:05:51','owner' => 'A-rhadys'),
			array('id' => '33','title' => 'PROF. NAYARITH LUCENA','content' => 'Tema: Virus Informáticos</br>Actividad para 1ero  año   A. B. C.  y  3er año    A, B, C</br>Investiga con la ayuda de tus familiares lo siguiente: Virus informáticos (definición, clasificación) formas de protegerse de los virus informáticos .</br>ACTIVIDAD:</br></br>Elabora un cuadro comparativo de los siguientes virus informáticos (caballo de Troya, gusanos, bombas de tiempo)   señalando lo siguiente: </br>b) 3 Características </br>c) Solución (o formas de eliminarlo del computador)</br></br> Puedes consultar las siguientes páginas:</br>https://www.youtube.com/watch?v=ZHfNaCuVzkg&t=16s</br>https://edu.gcfglobal.org/es/virus-informáticos-y-antivirus/que-es-un-virus-informático/1/</br>https://www.clasificaciónde.org/clasificación-de-virus-informático/</br>CRITERIOS DE EVALUACIÓN:</br>Contenido 16 ptos</br>Ortografía y redacción .2ptos</br>Pulcritud 2 ptos</br>Puedes enviar la actividad al correo: informáticalacandelaria1@gmail.com</br> Recuerda escribir la fecha nombre, apellido, año y sección de todas las actividades y guardar en tu portafolio.</br>','img' => '["assets\\/src\\/noticias\\/img\\/31.jpg"]','fecha' => '2020-04-07 15:58:45','owner' => 'A-rhadys'),
			array('id' => '34','title' => 'PROF. OSWALDO CONTRERAS','content' => 'Asignatura: Práctica de Oficina I</br>Curso: 5to año “A y B”</br>ACTIVIDAD N°1</br>Elabore un mapa conceptual sobre los documentos comerciales.</br>Contenido:</br>Definición</br>Clasificación</br>Importancia</br></br>Pauta de trabajo:</br>La actividad debe ser realizada utilizando los siguientes materiales:</br>Hoja de examen u hoja blanca (PUEDE SER RECICLADA)</br>Lápiz            Colores</br>Regla            Sacapuntas      Texto</br>Luego de realizada la actividad debe ser archivada en una carpeta para ser entregada en físico.   Todo trabajo debe llevar portada completa.</br></br>Asignatura: FUNDAMENTOS DE ECONOMÍA</br>Curso: 5to año “C”</br>ACTIVIDAD N°1</br>Elabore un mapa conceptual sobre los sectores que conforman la actividad económica venezolana.</br>Pauta de trabajo:</br>La actividad debe ser realizada utilizando los siguientes materiales:</br>Hoja de examen u hoja blanca  (PUEDE SER RECICLADA)</br>Lápiz          Colores</br>Regla          Sacapunta            Texto</br>Luego de realizada la actividad debe ser archivada en una carpeta para ser entregada en físico.   Todo trabajo debe llevar portada completa.</br>','img' => '["assets\\/src\\/noticias\\/img\\/32.gif"]','fecha' => '2020-04-07 16:45:26','owner' => 'A-rhadys'),
			array('id' => '35','title' => 'PROF. OSWALDO CONTRERAS','content' => 'Asignatura: Contabilidad</br>Curso: 4to año “A,B y C”</br>ACTIVIDAD   N°1</br>Elabore un esquema sobre la clasificación de las cuentas.</br>Este esquema debe tener todas las cuentas que comprenden los grupos de: Las cuentas Reales y las cuentas Nominales. </br></br>IMPORTANTE: No debe llevar conceptos, solo el nombre de cada una de las cuentas, las que pertenecen al grupo de las Reales y las que pertenecen a las Nominales, también deben especificar si de estas cuentas hay una sub división y cuáles son.</br></br>Pauta de trabajo:</br>La actividad debe ser realizada utilizando los siguientes materiales:</br>Hoja de examen u hoja blanca</br>Lápiz          Colores       Regla</br>Sacapuntas          Texto</br>Luego de realizada la actividad debe ser archivada en una carpeta para ser entregada en físico. Todo trabajo debe llevar portada completa.','img' => '["assets\\/src\\/noticias\\/img\\/33.jpg"]','fecha' => '2020-04-07 16:54:33','owner' => 'A-rhadys'),
			array('id' => '36','title' => 'PROFESOR RAFAEL ORTIZ ADMINISTRACIÓN','content' => 'Asignatura: Administración</br>Curso: 3er Año “A,B,C”</br>Actividad N°1</br>Con el tema QUE SE ENVIARÁ VÍA WHATSAPP  O CORREO , elabore un informe sobre la evaluación estratégica para combatir el corona virus tomando en cuenta que usted y su familia representan una empresa, y tiene el medicamento para combatirla , usted le dará el nombre a la empresa (Droguería).</br></br>Pauta de trabajo: debe llevar el siguiente esquema:</br>MISIÓN Y VISIÓN: </br>OBJETIVOS ESTRATÉGICOS:</br>OPORTUNIDADES Y AMENAZAS: </br>FORTALEZAS Y DEBILIDADES: </br>ESTRATEGIA DE NEGOCIOS: </br>ESTRATEGIAS OPERATIVAS: </br>PLAN ESTRATÉGICO: </br>PROYECTOS ESPECÍFICOS: </br>La actividad debe ser realizada utilizando los siguientes materiales:</br>Hoja  blanca o reciclada               Lápiz</br>Colores                Regla</br>Sacapuntas</br></br>Nota: Luego de realizada la actividad debe ser archivada en el portafolio para ser entregada en físico al momento que se indiquen en la página de la institución o por un aviso en la puerta del colegio, en su defecto puede ser enviada vía whatsapp o correo electrónico ortizprafaela@gmail.com ; todo trabajo debe llevar portada completa.</br>','img' => '["assets\\/src\\/noticias\\/img\\/34.jpg"]','fecha' => '2020-04-08 11:51:50','owner' => 'A-rhadys')
		);

		foreach ($news as $new) {
			$cedula = explode('-', $new['owner']);
			$cedula = $cedula[1];
			DB::table('news_data')->insert([
				'new_title' => $new['title'],
				'new_content' => $new['content'],
				'new_create_at' => $new['fecha'],
				'new_owner' => $cedula,
			]);
		}
		// $max = 75;
		// for($i=0; $i < $max; $i++) {
		// 	$img = $i % 3;
		// 	if ($img === 0) {
		// 		$imgList = '["http://cande800.run-us-west2.goorm.io/imgTest/post1-1.jpg"]';
		// 	}else if ($img === 1) {
		// 		$imgList = '["https:\/\/images.unsplash.com\/photo-1584463057921-c7770fecc471?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80","https:\/\/images.unsplash.com\/photo-1584463057921-c7770fecc471?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80","https:\/\/images.unsplash.com\/photo-1584891753006-ae9c155dc59a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80","https:\/\/images.unsplash.com\/photo-1475778057357-d35f37fa89dd?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80"]';
		// 	}else if ($img === 2) {
		// 		$imgList = null;
		// 	}
			
		// 	DB::table('news_data')->insert([
		// 'new_title' => Str::random(10),
		// 'new_content' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
		// 'new_create_at' => now()->sub($max - $i, 'minutes'),
		// 		'new_img' => $imgList,
		// 'new_owner' => ($i % 2) === 0 ? 'reckersito' : 'reckersote',
		// ]);
		// }
	}
}
